
services:
  web:
    image: specsmobile.azurecr.io/specsmobile:latest
    command: sh -c "uvicorn main:app --host 0.0.0.0"
    ports:
      - "80:80"
    environment:
      - DOCKER_USERNAME=${{ secrets.AZURE_CLIENT_ID }}
      - DOCKER_PASSWORD=${{ secrets.AZURE_CLIENT_SECRET }}